### ISSUE TITLE
Better offline screen

### ISSUE THREAD

**Issue by eankeen** [repl-it-discord/repl-it-electron#15]
When offline it would be better to have some offline page show up rather than error. I'll post photograph soon.

<img src="https://user-images.githubusercontent.com/24364012/53458319-7cc61e80-39ea-11e9-83da-f2ab406b2d04.png" width="500px"></img>

**Comment by leon332157** [comment]
I think this error will be sufficent for now. If you would like to add this feature, please do so.

**Comment by StarTrekRules** [comment]
I may be able to implement such feature, What is an example of what this offline page should look like?
It could be like a remade offline version of repl.it obviously not as good but still.
Or it could just be a screen telling you about the error or that you need an internet connection.

**Comment by leon332157** [comment]
I'm not sure since I think an alert window is enough.

**Comment by leon332157** [comment]
@EanKeen What do u think

**Comment by StarTrekRules** [comment]
@leon332157 Still, an offline primitive version of repl.it would be handy

**Comment by EanKeen** [comment]
@StarTrekRules Hello! 👋

So I think we have two options we can go for. We can have something that looks similar to this

![image](https://user-images.githubusercontent.com/24364012/56101308-59dac580-5ed7-11e9-9954-eda1ffd602a1.png)
Where the red text could say something like "No connection error: You cannot connect to repl.it because you don't have a network connection"

On the other hand, we could try to create some simple, custom page. Maybe a white background with some text, saying "Could not connect" "Please check your network connection" would be just fine.

**Comment by StarTrekRules** [comment]
@EanKeen It would not need to look similar, it would just need to function offline but now that I think of it that idea may make it more platform specific depending on where things like compilers are on a given system, otherwise I believe the alert window provides a detailed explanation of what went wrong

**Comment by EanKeen** [comment]
@StarTrekRules Why would this have anything to do with finding compilers on a given system whatsoever? If no connection can be made to repl.it, then we serve up this page. It's a more friendly user interface.

If we get to a point where the application finds compilers and tries to utilize them, we can modify the system accordingly. However, current planning for that seems excessive, as that doesn't seem to be on the roadmap at all.

**Comment by StarTrekRules** [comment]
@EanKeen I meant like, you can't connect to repl.it but you can use a primitive local interface instead until you get your internet back

**Comment by StarTrekRules** [comment]
@EanKeen The connection page should also have a refresh button to avoid them having to restart the app or use the menu bar to refresh

**Comment by leon332157** [comment]
The currerent implementation is by using event, when the window fail to load, it will trigger the alert function. So if we are to design a offline page we can do that, the problem is how should that page look like. And yes I think a refresh button is a good idea.

**Comment by EanKeen** [comment]
Yes, we can have a simple page that tells the user that no connection can be made. We can add a refresh button also. I'm thinking we can have a div horizontally and vertically centered. In that element, we can include a photograph depicting some typical 404 image. Under that, the message describing the connection problem, and buttons to refresh. Although, I think it would be better to just perform an AJAX request and if it succeeds, then we refresh the page.

**Comment by leon332157** [comment]
Planned for 2.1.1
